_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

homepage:
    path: /{_locale}/
    defaults: { _controller: app.main_controller:showAction, page: homepage }
    requirements:
        _locale: en|kr

show:
    path: /{_locale}/{page}
    defaults: { _controller: app.main_controller:showAction }
    requirements:
        _locale: en|kr
        page: classes|weddings|signature|about|contact