_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

homepage:
    path: /{_locale}/
    defaults: { _controller: app.main_controller:showAction, page: homepage }
    requirements:
        _locale: en|kr|jp|fr|cn

show:
    path: /{_locale}/{page}
    defaults: { _controller: app.main_controller:showAction }
    requirements:
        _locale: en|kr|jp|fr|cn
        page: classes|weddings|signature|provence_tour|flower_styling|about